// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplateManager.Infrastructure.DAL;

#nullable disable

namespace TemplateManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TemplateManager.Domain.Entities.HtmlTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HtmlTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3f6a1e4-8c2f-4a4d-a8e1-1b2c3d4e5f60"),
                            Content = "<h1>Invoice for {{Name}}</h1><p>Date: {{Date}}</p><p>Amount: {{Amount}}</p>",
                            Name = "Invoice Template"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d"),
                            Content = "<div><h2>Certificate of Completion</h2><p>This certifies that {{Name}} completed the course on {{Date}}</p></div>",
                            Name = "Certificate Template"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
